# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Delete Package Versions
      uses: actions/delete-package-versions@v5.0.0
      with:
        # Comma separated string of package version ids to delete.
        package-version-ids: 1
        # Owner of the repo containing the package version to delete. Defaults to the owner of the repo running the action.
    
        owner: ${{ github.repository_owner }}
        # Name of the package containing the version to delete.
    
        package-name: com.demo.demo-libs-test
        # Type of package. Can be one of container, maven, npm, nuget, or rubygems.
    
        package-type:  'maven'
        # Number of versions to delete starting with the oldest version. Defaults to 1.
        token: ${{ secrets.MAVEN_PKG_TOKEN }}

    - name: Maven Install
      run: mvn -DskipTests=true clean install
    - name: Build with Maven
      run: mvn -DskipTests=true -B package --file pom.xml
    - name: Publish to GitHub Packages Apache Maven
      run: mvn -DskipTests=true deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.MAVEN_PKG_TOKEN }}
    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v22
